---
- name: provision a geoblacklight instance
  hosts: all
  user: "{{ ansible_user }}"
  vars_files:
    - site_vars.yml
  gather_facts: true
  tasks:
    - name: Optionally include the site_secrets for non-tower deploys
      include_vars: file=site_secrets.yml
      when: tower_deploy is undefined
  roles:
    - { role: solr, become: yes, solr_version: "5.5.2" }
    - { role: geoblacklight, become: yes }
    - { role: chroot-sftp, become: yes, sftp_upload_root: "/opt/sftp/geodata"}
  environment:
    RAILS_ENV: "{{ project_app_env }}"
