---
- name: ensure tomcat7 packages are installed
  apt:
    name: '{{ item }}'
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes
    state: present
  with_items:
    - tomcat7
    - tomcat7-admin

- name: copy tomcat 7 config file
  template:
    src: server.xml.j2
    dest: /etc/tomcat7/server.xml
    mode: 0644

- name: ensure tomcat7 starts on boot
  service:
    name: tomcat7
    enabled: yes
